[phases.setup]
nixPkgs = ["php", "composer", "nodejs", "yarn"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "yarn",
  "yarn build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
